### ISSUE TITLE
Add email signup form + send an email? Do we have email?

### ISSUE THREAD

**Issue by marsrobertson** [EstoniaDAO/EstoniaDAO.github.io#4]
It's problematic who would manage email list...

**Comment by joeycharlesworth** [comment]
You can if you want to :)  In the meantime, I've created a substack for us. Want to add it to the site? Probably somewhere above the fold makes sense? <iframe src="https://estoniadao.substack.com/embed" width="480" height="320" style="border:1px solid #EEE; background:white;" frameborder="0" scrolling="no"></iframe>

**Comment by marsrobertson** [comment]
Done
